<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\UnauthorizedException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (TokenException $e) {
            return false;
        })->stop();
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof NotFoundHttpException) {
            return response()->json([
                'error' => 'Sorry, we\'re not supporting this route.',
            ], 404);
        }

        if ($e instanceof UnauthorizedException) {
            return response()->json([
                'error' => 'Unauthorized. Invalid Token.',
            ], 400);
        }


        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

    public function context(): array
    {
        return array_merge(parent::context(), [
            'foo' => 'bar',
        ]);
    }
}
